[package]
name = "wfc_words"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rayon = "1.7.0"
weighted_rand = "0.4.1"
regex = "1.9.5"
structopt = "0.3.26"
